import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/nav/Navbat";
import Sessionprovider from "@/components/session-provider";
import BgGlassmorphism from "@/components/BgGlassmorphism";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <BgGlassmorphism />
          {/* <Navbar /> */}
          <main className=" mx-auto  ">{children}</main>
        </ThemeProvider>
        <Sessionprovider />
      </body>
    </html>
  );
}
